services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - ENV=development
      - PYTHONPATH=/app
      # ADD THESE ENVIRONMENT VARIABLES:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEBUG_MODE=true
      - API_BASE_URL=http://localhost:8000
    restart: unless-stopped

volumes:
  uploads: