version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - ENV=development
      - PYTHONPATH=/app
    restart: unless-stopped

volumes:
  uploads: